package pid;

our $fields = [qw(
    SET_ID_PATIENT_ID
    PATIENT_ID_EXTERNAL_ID
    PATIENT_ID_INTERNAL_ID
    ALTERNATE_PATIENT_ID_PID
    PATIENT_NAME
    MOTHERS_MAIDEN_NAME
    DATE/TIME_OF_BIRTH
    SEX
    PATIENT_ALIAS
    RACE
    PATIENT_ADDRESS
    COUNTY_CODE
    PHONE_NUMBER_HOME
    PHONE_NUMBER_BUSINESS
    PRIMARY_LANGUAGE
    MARITAL_STATUS
    RELIGION
    PATIENT_ACCOUNT_NUMBER
    SSN_NUMBER_PATIENT
    DRIVERS_LICENSE_NUMBER_PATIENT
    MOTHERS_IDENTIFIER
    ETHNIC_GROUP
    BIRTH_PLACE
    MULTIPLE_BIRTH_INDICATOR
    BIRTH_ORDER
    CITIZENSHIP
    VETERANS_MILITARY_STATUS
    NATIONALITY
    PATIENT_DEATH_DATE_AND_TIME
    PATIENT_DEATH_INDICATOR
)];
